// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nursry.Infrastructure.Data;

namespace Nursry.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NursryContext))]
    [Migration("20190115140038_DetailsToBaseLog")]
    partial class DetailsToBaseLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nursry.Core.Entities.BottleContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Content");

                    b.HasKey("Id");

                    b.ToTable("BottleContents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e42a5065-dc76-49f0-ba59-343bb79594ab"),
                            Content = "Formula"
                        },
                        new
                        {
                            Id = new Guid("66fc7156-8f18-4899-8fa9-38ef14073e03"),
                            Content = "Breast milk"
                        });
                });

            modelBuilder.Entity("Nursry.Core.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<Guid?>("GenderId");

                    b.Property<string>("ImageUri");

                    b.Property<string>("LastName");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Nursry.Core.Entities.DiaperType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("DiaperTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5943d161-cee7-44e6-98df-d94745afd252"),
                            Title = "Pee"
                        },
                        new
                        {
                            Id = new Guid("c0b07ea3-f90d-4941-ad4f-e01135a6efce"),
                            Title = "Poo"
                        },
                        new
                        {
                            Id = new Guid("a15db759-ec19-45bf-b06c-c5faabee68aa"),
                            Title = "Both"
                        });
                });

            modelBuilder.Entity("Nursry.Core.Entities.FeedingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("FeedingTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81cbcf44-2e61-4660-8be0-99c22cb58c3f"),
                            Type = "Left Breast"
                        },
                        new
                        {
                            Id = new Guid("06efe9ad-f609-4131-b334-6307bf60a878"),
                            Type = "Right Breast"
                        },
                        new
                        {
                            Id = new Guid("2be3a084-8051-4c0e-b123-ae1d28cb0a38"),
                            Type = "Bottle"
                        },
                        new
                        {
                            Id = new Guid("756f69bb-57da-4d41-a595-7ff89b04af73"),
                            Type = "Meal"
                        });
                });

            modelBuilder.Entity("Nursry.Core.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("982376cd-c73c-43e5-bbec-11c95b89a444"),
                            Title = "Male"
                        },
                        new
                        {
                            Id = new Guid("a33c2cca-774a-418e-86c7-7a0b34c16937"),
                            Title = "Female"
                        });
                });

            modelBuilder.Entity("Nursry.Core.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid?>("ChildId");

                    b.Property<string>("Details");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Log");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Log");
                });

            modelBuilder.Entity("Nursry.Core.Entities.DiaperLog", b =>
                {
                    b.HasBaseType("Nursry.Core.Entities.Log");

                    b.Property<Guid?>("DiaperTypeId");

                    b.Property<DateTime>("TimeOfDiaperChange");

                    b.HasIndex("DiaperTypeId");

                    b.HasDiscriminator().HasValue("DiaperLog");
                });

            modelBuilder.Entity("Nursry.Core.Entities.FeedingLog", b =>
                {
                    b.HasBaseType("Nursry.Core.Entities.Log");

                    b.Property<DateTime>("EndTime");

                    b.Property<Guid?>("FeedingTypeId");

                    b.Property<DateTime>("StartTime");

                    b.HasIndex("FeedingTypeId");

                    b.HasDiscriminator().HasValue("FeedingLog");
                });

            modelBuilder.Entity("Nursry.Core.Entities.BottleFeedingLog", b =>
                {
                    b.HasBaseType("Nursry.Core.Entities.FeedingLog");

                    b.Property<decimal>("Amount");

                    b.Property<Guid?>("ContentsId");

                    b.HasIndex("ContentsId");

                    b.HasDiscriminator().HasValue("BottleFeedingLog");
                });

            modelBuilder.Entity("Nursry.Core.Entities.Child", b =>
                {
                    b.HasOne("Nursry.Core.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");
                });

            modelBuilder.Entity("Nursry.Core.Entities.Log", b =>
                {
                    b.HasOne("Nursry.Core.Entities.Child", "Child")
                        .WithMany("Logs")
                        .HasForeignKey("ChildId");
                });

            modelBuilder.Entity("Nursry.Core.Entities.DiaperLog", b =>
                {
                    b.HasOne("Nursry.Core.Entities.DiaperType", "DiaperType")
                        .WithMany()
                        .HasForeignKey("DiaperTypeId");
                });

            modelBuilder.Entity("Nursry.Core.Entities.FeedingLog", b =>
                {
                    b.HasOne("Nursry.Core.Entities.FeedingType", "FeedingType")
                        .WithMany()
                        .HasForeignKey("FeedingTypeId");
                });

            modelBuilder.Entity("Nursry.Core.Entities.BottleFeedingLog", b =>
                {
                    b.HasOne("Nursry.Core.Entities.BottleContent", "Contents")
                        .WithMany()
                        .HasForeignKey("ContentsId");
                });
#pragma warning restore 612, 618
        }
    }
}
